import { Theme } from '@components/theme'
import { createUseStyles } from 'react-jss'

export const useStyles = createUseStyles((theme: Theme) => ({
  container: {
    backgroundColor: theme.colors.light,
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'row',
    flexWrap: 'wrap',
    boxSizing: 'border-box',
    minHeight: '100vh',
    justifyContent: 'center',
    padding: '20px',
    gap: '20px',
    '@media (max-width: 1024px)': {
      flexDirection: 'column',
      alignItems: 'center',
    },
  },
  noImage: {
    color: theme.colors.slate_gray,
    display: 'flex',
  },
  image: {
    maxHeight: '50vh',
    objectFit: 'cover',
    width: '100%',
    borderRadius: 20,
  },
  buttons: {
    display: 'flex',
    justifyContent: 'center',
    gap: 16,
  },
  statusContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '10px',
    alignItems: 'center',
    justifyContent: 'flex-start',
    minWidth: '200px',
  },
  imageIsProcessing: {
    textAlign: 'center',
    color: theme.colors.bright_purple,
    fontWeight: 600,
    padding: '10px 16px',
    backgroundColor: theme.colors.bright_purple + '10',
    borderRadius: '8px',
  },
  modeEnTempsReelContainer: {
    textAlign: 'center',
    color: theme.colors.flame,
    fontWeight: 'bold',
    padding: '10px 16px',
    backgroundColor: theme.colors.flame + '10',
    borderRadius: '8px',
  },
  mqttStatusConnected: {
    marginTop: '10px',
    textAlign: 'center',
    color: '#10b981',
    fontWeight: 'bold',
    fontSize: '14px',
  },
  mqttStatusDisconnected: {
    marginTop: '10px',
    textAlign: 'center',
    color: theme.colors.flame,
    fontWeight: 'bold',
    fontSize: '14px',
  },
  camera: {
    display: 'flex',
    padding: 73,
    flexDirection: 'column',
    alignItems: 'center',
    flexShrink: 0,
    alignSelf: 'stretch',
    borderRadius: 10,
    background: '#ECECF0',
    position: 'relative',
    overflow: 'hidden',
  },
  closeButton: {
    position: 'absolute',
    top: 12,
    right: 12,
    width: 32,
    height: 32,
    borderRadius: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: theme.colors.flame,
    color: theme.colors.white,
    cursor: 'pointer',
    boxShadow: '0 2px 6px rgba(0,0,0,0.15)',
  },
  video: {
    width: '100%',
    height: '25vh',
    objectFit: 'cover',
    borderRadius: 10,
    backgroundColor: theme.colors.dark,
  },
  text: {
    display: 'flex',
    justifyContent: 'center',
    boxSizing: 'border-box',
    color: theme.colors.royal_blue,
  },
  containerCamera: {
    display: 'flex',
    flexDirection: 'column',
    gap: 24,
    width: '100%',
    flexShrink: 0,
  },
  loadingText: {
    textAlign: 'center',
    padding: '20px',
    color: theme.colors.slate_gray,
  },
  detectionsScrollContainer: {
    maxHeight: '500px',
    minHeight: '200px',
    overflowY: 'auto',
    overflowX: 'hidden',
    padding: '8px',
    scrollBehavior: 'smooth',
    display: 'block',
    '&::-webkit-scrollbar': {
      width: '10px',
    },
    '&::-webkit-scrollbar-track': {
      background: '#f1f1f1',
      borderRadius: '5px',
      margin: '4px 0',
    },
    '&::-webkit-scrollbar-thumb': {
      background: theme.colors.bright_purple,
      borderRadius: '5px',
      border: '2px solid #f1f1f1',
      '&:hover': {
        background: theme.colors.royal_blue,
      },
    },
    scrollbarWidth: 'thin',
    scrollbarColor: `${theme.colors.bright_purple} #f1f1f1`,
  },
  detectionsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(250px, 1fr))',
    gap: '16px',
  },
  noDetections: {
    textAlign: 'center',
    padding: '40px',
    color: theme.colors.slate_gray,
    fontSize: '14px',
  },
  detectionCard: {
    backgroundColor: '#fff',
    borderRadius: '12px',
    overflow: 'hidden',
    boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
    transition: 'transform 0.2s, box-shadow 0.2s',
    cursor: 'pointer',
    '&:hover': {
      transform: 'translateY(-4px)',
      boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
    },
  },
  detectionImage: {
    width: '100%',
    height: '180px',
    objectFit: 'cover',
    backgroundColor: '#f5f5f5',
  },
  noImagePlaceholder: {
    width: '100%',
    height: '180px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f5f5f5',
    color: theme.colors.slate_gray,
    gap: '8px',
  },
  detectionInfo: {
    padding: '12px',
  },
  detectionHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '8px',
  },
  detectionCount: {
    fontSize: '16px',
    fontWeight: 'bold',
    color: theme.colors.royal_blue,
  },
  detectionDate: {
    fontSize: '12px',
    color: theme.colors.slate_gray,
  },
  detectionObjects: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: '6px',
  },
  detectionTag: {
    fontSize: '12px',
    padding: '4px 8px',
    backgroundColor: theme.colors.bright_purple + '20',
    color: theme.colors.bright_purple,
    borderRadius: '4px',
    fontWeight: '500',
  },
}))
