import { Theme } from '@components/theme'
import { createUseStyles } from 'react-jss'

export const useStyles = createUseStyles((theme: Theme) => ({
  container: {
    backgroundColor: theme.colors.light,
    alignItems: 'center',
    display: 'flex',
    flexDirection: 'column',
    boxSizing: 'border-box',
    height: '90vh',
    justifyContent: 'center',
  },
  noImage: {
    color: theme.colors.slate_gray,
    display: 'flex',
  },
  image: {
    maxHeight: '50vh',
    objectFit: 'cover',
    width: '100%',
    borderRadius: 20,
  },
  buttons: {
    display: 'flex',
    justifyContent: 'center',
    gap: 16,
  },
  camera: {
    display: 'flex',
    padding: 73,
    flexDirection: 'column',
    alignItems: 'center',
    flexShrink: 0,
    alignSelf: 'stretch',
    borderRadius: 10,
    background: '#ECECF0',
    position: 'relative',
    overflow: 'hidden',
  },
  closeButton: {
    position: 'absolute',
    top: 12,
    right: 12,
    width: 32,
    height: 32,
    borderRadius: 10,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: theme.colors.flame,
    color: theme.colors.white,
    cursor: 'pointer',
    boxShadow: '0 2px 6px rgba(0,0,0,0.15)',
  },
  video: {
    width: '100%',
    height: '25vh',
    objectFit: 'cover',
    borderRadius: '10px',
    backgroundColor: theme.colors.dark,
  },
  text: {
    display: 'flex',
    justifyContent: 'center',
    boxSizing: 'border-box',
    color: theme.colors.royal_blue,
  },
  containerCamera: {
    display: 'flex',
    flexDirection: 'column',
    gap: 24,
    flexShrink: 0,
  },
}))
